#!/bin/bash
LOG_CMD="git log -1 --pretty=format:"
ARGS=''
COMMIT=''

# iterate over args
for i; do
	if [[ "$i" = -* ]]; then
		ARGS="$ARGS $i"
	elif [[ "$i" =~ '^[0-9]+$' ]] && [[ "$ARGS" =~ '-m\s*$' ]]; then
		ARGS="$ARGS $i"
	elif [[ -n "$COMMIT" ]]; then
		echo "Multiple commits specified? Weird."
		exit 1
	else
		COMMIT=$i
	fi
done

export GIT_AUTHOR_NAME="$(${LOG_CMD}%an $COMMIT)"
export GIT_AUTHOR_EMAIL="$(${LOG_CMD}%ae $COMMIT)"
export GIT_AUTHOR_DATE="$(${LOG_CMD}%ad $COMMIT)"
export GIT_COMMITTER_NAME="$(${LOG_CMD}%cn $COMMIT)"
export GIT_COMMITTER_EMAIL="$(${LOG_CMD}%ce $COMMIT)"
export GIT_COMMITTER_DATE="$(${LOG_CMD}%cd $COMMIT)"
export GIT_EDITOR="grep -vE '^#'"

echo "Author:     ${GIT_AUTHOR_NAME} <${GIT_AUTHOR_EMAIL}>"
echo "AuthorDate: ${GIT_AUTHOR_DATE}"
echo "Commit:     ${GIT_COMMITTER_NAME} <${GIT_COMMITTER_EMAIL}>"
echo "CommitDate: ${GIT_COMMITTER_DATE}"
echo
git cherry-pick --no-commit $ARGS $COMMIT
git ci
