#!/bin/bash
MERGED_TO=${1:-master}

for i in $(git branch | cut -c3- | sed -re '/->/d; /^'${MERGED_TO}'$/d' ); do
	echo -n "$i: "
	git branch --contains $i | cut -c3- | grep "^${MERGED_TO}\$" || echo
done | grep " ${MERGED_TO}\$" | cut -d: -f1
