#!/bin/bash
#
# Copyright (c) 2013-2014 David Ingram
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

LOG_CMD="git log -1 --pretty=format:"
export GIT_COMMITTER_NAME="$(${LOG_CMD}%an)"
export GIT_COMMITTER_EMAIL="$(${LOG_CMD}%ae)"
export GIT_COMMITTER_DATE="$(${LOG_CMD}%ad)"
export GIT_EDITOR="grep -vE '^#'"

echo "Author:        ${GIT_COMMITTER_NAME} <${GIT_COMMITTER_EMAIL}>"
echo "AuthorDate:    ${GIT_COMMITTER_DATE}"
echo "OldCommit:     $(${LOG_CMD}%cn) <$(${LOG_CMD}%ce)>"
echo "OldCommitDate: $(${LOG_CMD}%cd)"
echo "Commit:        ${GIT_COMMITTER_NAME} <${GIT_COMMITTER_EMAIL}>"
echo "CommitDate:    ${GIT_COMMITTER_DATE}"
echo
git ci --amend
